# Generated by Django 5.2.17 on 2026-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código alfanumérico en mayúsculas (ej: HUMM2026, PILOTO-VALPO)', max_length=32, unique=True, verbose_name='Código de invitación')),
                ('descripcion', models.CharField(blank=True, help_text='Contexto o grupo del piloto asignado a esta invitación', max_length=150, verbose_name='Descripción / Destinatario')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('max_usos', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para usos ilimitados (código general de control)', null=True, verbose_name='Límite de usos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='Usos registrados')),
                ('creada_el', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('expira_el', models.DateTimeField(blank=True, help_text='Fecha y hora límite de validez. Dejar vacío si no expira.', null=True, verbose_name='Expira el')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-creada_el'],
            },
        ),
    ]
