# Generated by Django 5.2.17 on 2026-09-27 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_invitacion', models.CharField(blank=True, max_length=32, verbose_name='Código de invitación utilizado')),
                ('registrado_el', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_piloto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Piloto',
                'verbose_name_plural': 'Perfiles de Piloto',
            },
        ),
    ]
