# Generated by Django 5.2.17 on 2026-09-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilpiloto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpiloto',
            name='tipo_cuenta',
            field=models.CharField(choices=[('PILOTO', 'Piloto'), ('ADMIN', 'Administrador'), ('GRATIS', 'Gratis (Futuro)'), ('PRO', 'Pro (Futuro)')], default='PILOTO', max_length=20, verbose_name='Modalidad / Tipo de cuenta'),
        ),
    ]
