# Generated by Django 5.2.17 on 2026-09-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilpiloto_tipo_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpiloto',
            name='estado_suscripcion',
            field=models.CharField(blank=True, default='ACTIVA', max_length=20, verbose_name='Estado de suscripción'),
        ),
        migrations.AddField(
            model_name='perfilpiloto',
            name='fecha_fin_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin del plan'),
        ),
        migrations.AddField(
            model_name='perfilpiloto',
            name='fecha_inicio_plan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio del plan'),
        ),
        migrations.AlterField(
            model_name='perfilpiloto',
            name='tipo_cuenta',
            field=models.CharField(choices=[('PILOTO', 'Piloto'), ('ADMIN', 'Administrador'), ('GRATIS', 'Fogata Gratis'), ('PRO', 'Fogata Pro')], default='PILOTO', max_length=20, verbose_name='Modalidad / Tipo de cuenta'),
        ),
    ]
