# Generated by Django 5.2.17 on 2026-09-28 18:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('suspender_usuario', 'Suspensión de cuenta'), ('reactivar_usuario', 'Reactivación de cuenta'), ('enviar_reset_password', 'Envío de recuperación de contraseña')], max_length=40, verbose_name='Acción')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('detalles', models.TextField(blank=True, verbose_name='Detalles / Motivo')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_admin_ejecutadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_admin_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario afectado')),
            ],
            options={
                'verbose_name': 'Auditoría Administrativa',
                'verbose_name_plural': 'Auditorías Administrativas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EventoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('registro', 'Registro de cuenta'), ('login', 'Inicio de sesión'), ('crear_cancion', 'Creación de canción'), ('editar_cancion', 'Edición de canción'), ('tocar_cancion', 'Uso de Modo Tocar (Canción en atril)'), ('crear_fogata', 'Creación de Fogata'), ('editar_fogata', 'Edición de Fogata'), ('tocar_fogata', 'Uso de Modo Tocar (Fogata en atril)'), ('crear_sesion_compartida', 'Creación de sesión compartida'), ('abrir_sesion_compartida', 'Apertura de sesión compartida por invitado')], db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('objeto_tipo', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Tipo de objeto')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos mínimos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_uso', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Uso',
                'verbose_name_plural': 'Eventos de Uso',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo_evento', 'fecha'], name='gestion_eve_tipo_ev_ab7a4d_idx'), models.Index(fields=['usuario', 'fecha'], name='gestion_eve_usuario_5f7e21_idx'), models.Index(fields=['usuario', 'tipo_evento'], name='gestion_eve_usuario_0c2e93_idx')],
            },
        ),
    ]
