# Generated by Django 5.2.17 on 2026-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_auditoriaadmin_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventouso',
            name='tipo_evento',
            field=models.CharField(choices=[('registro', 'Registro de cuenta'), ('login', 'Inicio de sesión'), ('crear_cancion', 'Creación de canción'), ('editar_cancion', 'Edición de canción'), ('tocar_cancion', 'Uso de Modo Tocar (Canción en atril)'), ('crear_fogata', 'Creación de Fogata'), ('editar_fogata', 'Edición de Fogata'), ('tocar_fogata', 'Uso de Modo Tocar (Fogata en atril)'), ('crear_sesion_compartida', 'Creación de sesión compartida'), ('abrir_sesion_compartida', 'Apertura de sesión compartida por invitado'), ('ver_pro', 'Visualización de página Fogata Pro'), ('alcanzar_limite_canciones', 'Intento de creación sobre límite de canciones'), ('alcanzar_limite_fogatas', 'Intento de creación sobre límite de Fogatas'), ('iniciar_pago', 'Inicio de checkout Flow'), ('pago_confirmado', 'Confirmación de pago aprobado Flow'), ('pago_rechazado', 'Notificación de pago rechazado Flow'), ('upgrade_pro', 'Primera activación de Fogata Pro'), ('renovacion_pro', 'Renovación de vigencia Fogata Pro')], db_index=True, max_length=40, verbose_name='Tipo de evento'),
        ),
    ]
