# Generated by Django 5.2.17 on 2026-09-26 21:38

import apps.fogatas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fogata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Fogata en la playa, Acústicos 90s, Ensayo viernes', max_length=150, verbose_name='Nombre de la Fogata')),
                ('descripcion', models.TextField(blank=True, help_text='Notas generales del repertorio o evento', verbose_name='Descripción / Contexto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Fogata',
                'verbose_name_plural': 'Fogatas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FogataCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden en el setlist')),
                ('nota_sesion', models.CharField(blank=True, help_text='Ej: Bajar un tono, solo primera estrofa, unir con siguiente', max_length=200, verbose_name='Nota para esta sesión')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_fogatas', to='canciones.cancion', verbose_name='Canción')),
                ('fogata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones_asociadas', to='fogatas.fogata', verbose_name='Fogata')),
            ],
            options={
                'verbose_name': 'Canción en Fogata',
                'verbose_name_plural': 'Canciones en Fogata',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='fogata',
            name='canciones',
            field=models.ManyToManyField(blank=True, related_name='fogatas', through='fogatas.FogataCancion', to='canciones.cancion', verbose_name='Canciones'),
        ),
        migrations.CreateModel(
            name='SesionCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.fogatas.models.generar_token_seguro, max_length=64, unique=True, verbose_name='Token de acceso')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('expira_el', models.DateTimeField(default=apps.fogatas.models.fecha_expiracion_por_defecto, verbose_name='Expira el')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fogata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_compartidas', to='fogatas.fogata', verbose_name='Fogata')),
            ],
            options={
                'verbose_name': 'Sesión Compartida',
                'verbose_name_plural': 'Sesiones Compartidas',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.AddConstraint(
            model_name='fogatacancion',
            constraint=models.UniqueConstraint(fields=('fogata', 'cancion'), name='unique_fogata_cancion'),
        ),
    ]
