# Generated by Django 5.2.17 on 2026-10-02 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commerce_order', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Orden de Comercio (Fogata)')),
                ('flow_order', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Orden oficial Flow')),
                ('flow_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Token de sesión Flow')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID de solicitud de checkout (Prevención doble submit)')),
                ('ambiente', models.CharField(choices=[('SANDBOX', 'Sandbox (Pruebas)'), ('PRODUCTION', 'Producción (Real)')], db_index=True, default='SANDBOX', max_length=20, verbose_name='Ambiente')),
                ('plan', models.CharField(choices=[('PRO_6M', 'Fogata Pro Semestral (6 meses)'), ('PRO_12M', 'Fogata Pro Anual (12 meses)')], max_length=20, verbose_name='Plan contratado')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto en CLP')),
                ('moneda', models.CharField(default='CLP', max_length=5, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('CREADA', 'Creada localmente'), ('PENDIENTE', 'En espera de pago (Checkout Flow)'), ('PAGADA', 'Pagada y confirmada'), ('RECHAZADA', 'Rechazada por medio de pago'), ('ANULADA', 'Anulada o expirada por usuario'), ('ERROR_TECNICO', 'Error de conectividad transitorio'), ('ERROR_VALIDACION', 'Discrepancia en monto/moneda/orden')], db_index=True, default='CREADA', max_length=25, verbose_name='Estado')),
                ('pro_aplicado', models.BooleanField(db_index=True, default=False, verbose_name='Beneficio Pro aplicado')),
                ('creada_el', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creada el')),
                ('actualizada_el', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('pagada_el', models.DateTimeField(blank=True, null=True, verbose_name='Pagada el')),
                ('fecha_inicio_plan', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio del período')),
                ('fecha_fin_plan', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin del período')),
                ('detalles_error', models.TextField(blank=True, verbose_name='Detalles técnicos / Discrepancias')),
                ('flow_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos técnicos sanitizados de Flow')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
                'ordering': ['-creada_el'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='pagos_orden_usuario_5671cf_idx'), models.Index(fields=['ambiente', 'estado'], name='pagos_orden_ambient_4542ba_idx'), models.Index(fields=['estado', 'creada_el'], name='pagos_orden_estado_96c4f8_idx')],
            },
        ),
    ]
