# Generated by Django 5.2.17 on 2026-09-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre de la canción', max_length=200, verbose_name='Título')),
                ('artista', models.CharField(blank=True, help_text='Nombre del intérprete o compositor', max_length=200, verbose_name='Artista / Banda')),
                ('contenido', models.TextField(help_text='Texto íntegro tal como fue copiado/escrito. Se preservan espacios y saltos de línea.', verbose_name='Contenido (Letra + Acordes)')),
                ('tonalidad', models.CharField(blank=True, help_text='Tono base (ej: G, Am, C#m)', max_length=10, verbose_name='Tono')),
                ('capo', models.PositiveSmallIntegerField(default=0, help_text='Traste del cejillo (0 = sin capo)', verbose_name='Capo / Cejillo')),
                ('afinacion', models.CharField(blank=True, default='Estándar (E A D G B E)', max_length=50, verbose_name='Afinación')),
                ('notas_personales', models.TextField(blank=True, help_text='Rasgueo, ritmo, intro, anotaciones personales', verbose_name='Notas de interpretación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['titulo', 'artista'],
            },
        ),
    ]
