# Generated by Django 5.2.17 on 2026-09-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='capo',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Traste del cejillo (0 = sin capo)', verbose_name='Capo / Cejillo'),
        ),
    ]
