# Generated by Django 5.2.17 on 2026-09-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0002_alter_cancion_capo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
