# Generated by Django 5.2.17 on 2026-09-27 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canciones', '0003_cancion_propietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
